[#setup]

= Setting Up Your Starknet Development Environment

This chapter will guide you through the process of setting up your Starknet development environment.

We need to install tools that allow us to interact with Starknet and compile Cairo code. The following tools are suggested:

. https://github.com/xJonathanLEI/starkli[Starkli] is a command-line interface that allows you to interact with Starknet. This is one of the tools that allow us to interact with Starknet, however, it is not the only one. We will cover other tools in the Chapter 3 (e.g., the Starknet JavaScript/Python/Rust SDK, Hardhat, or Protostar).
. https://github.com/software-mansion/scarb[Scarb] is the package manager for Cairo. Among other things, it allows us to compile Cairo code to Sierra, the intermediate language between high-level Cairo and the low-level Cairo Assembly (CASM).

[NOTE]
====
For support or feedback regarding this critical section, please visit our https://github.com/starknet-edu/starknetbook/issues[Issues section of the Book's GitHub repository] or reach out to espejelomar directly on Telegram.
====

== Starkli Installation

Starkliup is the installer for the Starkli environment, and it can be easily installed using the command line with curl:

[source,shell]
----
curl https://get.starkli.sh | sh
----

Restart the terminal after executing the command. Once starkliup has been successfully installed, it can then be used to install Starkli:

[source,shell]
----
starkliup
----

Upon executing the command, you'll see the following:

Restart the terminal and run the following command to verify the installation:

[source,shell]
----
starkli --version
----

To upgrade to the latest version of Starkli simply follow the past steps again.

== The Scarb Package Manager Installation

In this section we go into the fundamentals of Scarb, if you want to get deeper refer to the https://book.starknet.io/chapter_2/scarb.html[Scarb subchapter in Chapter 2].

Scarb is compatible with macOS, Linux, and Windows operating systems.

For macOS and Linux users, open your terminal and execute the following command:

[source, bash]
----
$ curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----

You can run the same command to upgrade it.

Scarb's installation on Windows requires manual setup. Follow the steps in the https://docs.swmansion.com/scarb/download#install-via-installation-script[Scarb documentation] to install it.

Restart the terminal and run the following command to verify the installation:

[source, bash]
----
$ scarb --version
----

You can run the same command to upgrade it:

[source, bash]
----
curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----

You know are ready to start writing Cairo code and deploying it to Starknet!
