[id="glossary"]
= Glossary
:Cairo_header: pass:quotes[_Cairo programming language term_]

[#account-abstraction]
== account abstraction

Account abstraction enables more flexible account management. Rather than the protocol determining an account’s behaviour, an account contract, which is a smart contract with programmable logic, defines a user’s account.

[#account_contract]
== account contract

An L2 smart contract, implemented in Cairo, with programmable logic that implements a user account on Starknet.

.See also

* xref:#account-abstraction[account abstraction]

[#account_descriptor]
== account descriptor

A JSON file detailing the wallet’s address and public key.

.See also

xref:#signer[signer]

[#api]
== API

An Application Programming Interface (API), is a software intermediary that enables two or more computers to communicate with each other. An API describes how to build or use such a connection or interface.

The Starknet Node API uses the Remote Procedure Call (RPC) architectural style, written in JSON format. For complete information on the Starknet Node API in JSON RPC format, see link:https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json[`starknet_api_openrpc.json`] on Github.

.See also

* xref:#rpc[RPC]

[#starknet-application]
== application

In Starknet, an application is a collection of L1 and L2 contracts that collectively implement a business flow.

[#application-developers]
== application developer

Someone that develops a Starknet application. They write and deploy contracts on Starknet and Ethereum.


[#array]
== array

{Cairo_header}

A collection of elements of the same type. Arrays in Cairo are immutable and cannot be overwritten, you can only append items to the end of an array.

You can create and use array methods by using the `ArrayTrait` trait from the Cairo core library.

[#blob]
== blob

{Cairo_header}

A sequence of raw binary data without a predefined data type or format, commonly used for handling arbitrary and generic data in a flexible manner.


[#blocks-previously-known-as-batches]
== blocks (previously known as batches)

Ordered sets of Starknet transactions that are run using the Starknet OS, resulting in one aggregated state change that is then committed to the Starknet L1 Core Contract.

A block has the following identifiers:

block hash:: A unique stable identifier that can be used to query and refer to the block.
block number:: An ordinal number representing the location of the block in the sequence of accepted blocks in Starknet. Be aware that a block’s number can change over time, and a given number can refer to different blocks at different points in time. For example, in the event of L1 chain reorders.

[#builtin]
== builtin

{Cairo_header}

A predefined optimised low-level execution unit that is added to the Cairo CPU board to perform predefined computations that are expensive to perform in vanilla Cairo, including range-checks, Pedersen hash calculations, and ECDSA.

[#cairo-step]
== Cairo step

A fundamental computational operation or instruction in the Cairo language. The smallest unit of execution within the Cairo VM, typically involving mathematical, logical, or control-flow operations that collectively define the behaviour of a program.


[#cairovm]
== Cairo VM

The Cairo Virtual Machine (VM) is software that knows how to execute compiled Cairo byte-code. The result of this execution is the program trace that can then be sent to a STARK prover in order to prove the validity of the instruction expressed in the Cairo code.

[#component]
== component

A component closely resembles a contract and encompasses storage variables, events, and external and internal functions. Unlike a standalone contract, a component cannot be deployed independently. Its code becomes integrated into the contract to which it is attached.

[#contract_class]
== contract class

The definition of a contract. It includes Cairo byte code, hint information, entry point names, and everything that defines its semantics.

[#contract instance]
== contract instance

The program that encodes the implemented application business logic, including the application data structures and handling of specific transactions sent by users. Specifically, the Starknet contract encodes valid state transitions for the application.

[#dictionaries]
== dictionaries

{Cairo_header}

A data structure in Cairo that holds a collection of key-value pairs where each key is unique and has a corresponding value. Similar to maps, hash tables, and associative arrays in other programming languages.

[#full-state-node]
== full state node

A node in the Starknet network that is used only for querying the current Starknet state. It can independently, without querying additional nodes, answer queries about the current state of the Starknet network, including the L1 state. A full state node does not batch transactions or prove batches.

[#import]
== import

{Cairo_header}

Enables reusing functions, structs, and enums in a Cairo program from another file.

In Cairo, as is the case with other programming languages, keeping an entire program in one source file is undesirable and impractical. Importing a module from another file facilitates modularity.

[#multicall]
== multicall

A single transaction that executes multiple bundled transactions, which are signed once on Starknet. If one call fails, the entire operation is aborted.

Use a multicall to prevent leaving your system in an inconsistent state.

[#prover]
== prover

A separate process, either an online service or internal to the node, that receives the output of Cairo programs and generates STARK proofs to be verified. The prover submits the STARK proof to the verifier that registers the fact on L1.

Provers serve as the second line of verification in the Starknet network. Their main task is to validate the work of the sequencers when they receive the block produced by the sequencer, and to generate proofs that these processes were correctly performed.

.See also

* xref:#SHARP[SHARP]
* xref:#verifier[verifier]

[#rpc]
== RPC

Remote Procedure Call (RPC) is an API protocol that enables a program to request a service from another program located on a computer in a network without needing to understand the network's details. RPC uses the Client/Server model, where the client is the program sending a request, and the server is the program that provides the service.

In Starknet, the RPC API provides clients access to the Starknet network, enabling you to execute subroutines without requiring you to explicitly code the details of your remote interactions.

.See also

* xref:#api[API]

[#sequencer]
== sequencer

The backbone of the Starknet network, akin to Ethereum’s validators. A sequencer ushers transactions into the system.

Networks like Starknet that use Validity Rollups outsource transaction processing to sequencers and then verify their work.

[#SHARP]
== SHARP

The Shared Prover (SHARP), is a mechanism used in Starknet that aggregates multiple Cairo programs from different users, each containing different logic. These Cairo programs are then executed together, generating a single proof common to all the programs.


[#sierra]
== Sierra

An intermediate representation between Cairo and Casm. Ensures transaction provability while addressing issues related to reverted transactions and potential Denial of Service (DoS) attacks. Sierra serves as a secure layer between Cairo code and provable code, Casm, contributing to the overall security and integrity of the Starknet system.

.Additional resources

* link:https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/cairo-and-sierra/[Cairo and Sierra]

[#signer]
== signer

The component of a Starknet account that authorizes a transaction and is decoupled from the account. It is a keypair consisting of a private and public key.

A smart contract with a private key for signing transactions.

.See also

xref:#account_descriptor[account descriptor]

[#stark]
== STARK

A proof system that uses cutting-edge cryptography to provide polylogarithmic verification resources and proof size, with minimal and post-quantum-secure assumptions.

[#starknet-l1-core-contract]
== Starknet L1 Core Contract

Defines the state of Starknet by storing:

* The commitment to the L2 state.
* The Starknet OS program hash – effectively defining the version of Starknet the network is running.

The committed state on the L1 Core Contract acts as the consensus mechanism of Starknet,that is, the system is secured by the L1 Ethereum consensus. In addition to maintaining the state, the Starknet L1 Core Contract is the main hub of operations for Starknet on L1. Specifically:

* It stores the list of allowed verifier contracts that can verify state update transactions
* It facilitates cross-layer interaction between L1 and L2.

[#starknet-os]
== Starknet OS

Updates the L2 state of the system based on transactions that are received as inputs. Effectively facilitates the execution of the (Cairo-based) Starknet contracts. The OS is Cairo-based and is essentially the program whose output is proven and verified using the STARK-proof system. Specific system operations and functionality available for Starknet contracts are available as calls made to the OS.

[#sequencer-node]
== sequencer node

The main node of the Starknet network. It implements the core functionality of sequencing transactions submitted to it. It executes the Starknet OS Cairo program with the relevant inputs, proves the result using the proving service or some internal STARK prover, and eventually updates the network state on the Starknet Core Contract.

[#starknet-state]
== Starknet state

The state is composed of contracts’ code and contracts’ storage.

.Additional resources

* link:https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/starknet-state/[Starknet state]


[#transaction]
== transaction

An invocation of a specific state-transition logic defined by a contract. Syntactically, a transaction has a well-defined structure that includes all the necessary metadata and an arbitrary data payload. The semantics of the transaction are defined by the invoked contract.

[#starknet-users]
== Starknet users

The users that interact with Starknet sequencer nodes and, if necessary, with L1 contracts. These users, whether human or automated, are the agents that submit transactions to the Starknet network.

[#statediff]
== state diff

Contains information on every contract whose storage was updated and additional information on contract deployments.

[#verifier]
== verifier

An L1 smart contract, crafted in Solidity, designed to validate STARK proofs from the Shared Prover (SHARP).
