[id="glossary"]
= Glossary

[#toc-application-developers]
== application developer

Someone that develops a Starknet application. They write and deploy contracts on Starknet and Ethereum.

[#toc-blocks-previously-known-as-batches]
== blocks (previously known as batches)

Ordered sets of Starknet transactions that are run using the Starknet OS, resulting in one aggregated state change that is then committed to the Starknet L1 core contract. A block has:

* a block hash – a unique stable identifier that can be used to query and refer to the block.
* a block number – an ordinal number representing the location of the block in the sequence of accepted blocks in Starknet. Note, a block’s number may change over time. Also, a given number may refer to different blocks at different points in time, e.g., in the event of L1 chain re-orders.

[#toc-full-state-node]
== full state node

A node in the Starknet network that is used only for querying the current Starknet state. It can independently (i.e., without/o querying additional nodes) answer queries about the current state of the Starknet network, including the L1 state. It does not batch transactions or prove batches.


[#toc-starknet-application]
== Starknet application

A collection of contracts (L1 and L2) that collectively implement a business flow.

[#toc-starknet-contract]
== Starknet contract

The program that encodes the implemented application business logic. This includes the application data structures and handling of specific transactions sent by users. Specifically, the Starknet contract encodes valid state transitions for the application.

* Starknet account contracts: Given account abstraction, user accounts are not implemented at the protocol level. Some contracts will, therefore, need to implement the concept of user accounts; these are called Account Contracts. The exact implementation depends on the contract; but, technically, these are Starknet contracts that are implemented in Cairo.

[#toc-starknet-l1-core-contract]
== Starknet L1 core contract

This L1 contract defines the state of the system by storing the commitment to the L2 state. The contract also stores the Starknet OS program hash – effectively defining the version of Starknet the network is running. The committed state on the L1 core contract acts as the consensus mechanism of Starknet, i.e., the system is secured by the L1 Ethereum consensus. In addition to maintaining the state, the Starknet L1 Core Contract is the main hub of operations for Starknet on L1. Specifically:

* It stores the list of allowed verifiers (contracts) that can verify state update transactions
* It facilitates L1 ↔ L2 interaction

[#toc-starknet-os]
== Starknet OS

Updates the L2 state of the system based on transactions that are received as inputs. Effectively facilitates the execution of the (Cairo-based) Starknet contracts. The OS is Cairo-based and is essentially the program whose output is proven and verified using the STARK-proof system. Specific system operations and functionality available for Starknet contracts are available as calls made to the OS.

[#toc-starknet-sequencer-node]
== Starknet sequencer node

The main node of the Starknet network. It implements the core functionality of sequencing transactions submitted to it. It executes the Starknet OS Cairo program with the relevant inputs, proves the result using the Proving Service or some internal STARK prover, and eventually updates the network state on the Starknet Core Contract.

[#toc-starknet-state]
== Starknet state

The state is composed of contracts’ code and contracts’ storage.

[#toc-starknet-transaction]
== Starknet transaction

An invocation of a specific state-transition logic that’s defined by a contract. Syntactically, a transaction has a well-defined structure that includes all the necessary metadata and an arbitrary data payload. The semantics of the transaction is defined by the invoked contract.

[#toc-starknet-users]
== Starknet users

The users that interact with Starknet sequencer nodes and, if necessary, with L1 contracts. These users, whether human or automated, are the agents that submit transactions to the Starknet network.

[#toc-starknet-Prover]
== Prover

Provers serve as the second line of verification in the Starknet network. Their main task is to validate the work of the sequencers when they receive the block produced by the sequencer, and to generate proofs that these processes were correctly performed.
SHARP, which stands for "Shared Prover", is a mechanism used in Starknet that aggregates multiple Cairo programs from different users, each containing different logic. These Cairo programs are then executed together, generating a single proof common to all the programs.

[#toc-starknet-sequencer]
== sequencer

Sequencers are the backbone of the Starknet network, akin to Ethereum’s validators. They usher transactions into the system. For networks like Starknet and other platforms utilizing Validity rollups, a similar parallel is drawn. These networks outsource transaction processing to specialized entities and then verify their work. These specialized entities in the context of Validity rollups are known as _sequencers_.

[#toc-starknet-Verifier]
== Starknet Verifier

A Solidity verifier is an L1 smart contract, crafted in Solidity, designed to validate STARK proofs from SHARP (Shared Prover).

[#toc-starknet- node]
== Starknet node

A computer, equipped with Starknet software, that contributes significantly to the network's operations. Nodes are vital for the Starknet ecosystem's functionality, security, and overall health. Without nodes, the Starknet network would not be able to function effectively.
Nodes serve as auditors of the network, maintaining the state of the network, such as how much Bitcoin each participant owns or the current state of a specific smart contract. They accomplish this by processing transactions and preserving a record of all transactions.